### ISSUE TITLE
Assignment 04 Feedback

### ISSUE THREAD

**Issue by hello-owlex** [kanomtang/sleepless#32]
There are no unit tests! Did you do the in class activity?

Edit, now I am a little bit confused. I see commits like GH-23 (https://github.com/kanomtang/sleepless/commit/d59de6fa480f95edfe16ad2353a223f7299719e7) which shows a unit test being created but I do not see farmapp/test/farmapp/controller/RuntimeImplementation/TestPrompt.java in your source tree. Can someone in your group send me a message on Facebook so I can understand what your group is doing :)

**Comment by hello-owlex** [comment]
Updated Feedback: @kanomtang @nithirot007 @beeforce (tagging you so you see this comment)

**Assignment 02 (Design) Feedback:**

- Looks good! here is some feedback!
- There are no implementation details on the methods. There was generally one sentence provided explaining the method, but no “step-by-step” details explaining implementation. For example:

```
public static void havestPlant()
-To havest plant in garden bed.
```
Will all fruits be harvested? Or one fruit at a time? Can you select what fruit to harvest? What will happen to the harvested fruit? Etc. How will this look in the code?
```
Special Case :
-If the plant die or not product fruit yet the havestPalnt will stop.
```
It would be good to explain the behavior in more depth. How will the user know? Will it print a message out to the screen? 
In your diagram, it looks like the plants will be stored in the inventory. It might be good to have a “Garden Bed” or some other data structure to hold the plants.

**Assignment 04 (Unit Test) Feedback:**
-Looks good!
-I see some tests that don't assert anything. These tests increase your code coverage but they don't add any value! For example:
```
@Test
	public void testWaterDurian(){
		Durian d = new Durian();
		d.waterPlant();
	}
```
-how do we know the plant was watered? We need to assert that plant was watered to check.
-One of the most important things to test is your controller. That has the most logic. We need to test cases like what happens when we plant many plants? What happens when we harvest only one plant? Etc.
-Thanks for merging your changes back to master for me :)

**Comment by kanomtang** [comment]
I will answer the first question. Yes, they will harvest all plant that Plant can produce a Fruit (Mature stage).

**Comment by kanomtang** [comment]
In the 2nd question We will update the code when The plant are harvested  it will show some message.
In the 3rd question We will fix some point in diagram to latest version.
Thank you for your attention.
