### ISSUE TITLE
Milestone 01 Feedback

### ISSUE THREAD

**Issue by hello-owlex** [kanomtang/sleepless#8]
Sleepless FEEDBACK
**Design (Assignment 02)**

- Did you submit? I did not receive a design. Please let me know! By email, facebook message, or comment on this issue.

**Implementation (Assignment 03)**

- Menu is stuck in infinite loop
- Everything is under one package. Project structure and organization could be improved.
- Plant values are hard coded
- Plants should implement interface, not extend a parent class.
- I see some work was done, but it seems very incomplete. Is everyone in the group working together?
- See me during office hours if you want to hear my suggestions for the above feedback
- Lastly, you were one of four teams to finish any work. Thank you!!

**Comment by kanomtang** [comment]
Ok. We will fix with your suggestion after holidays. Thx for your attention on our work.

**Comment by kanomtang** [comment]
P.s my's friends Buri and ton  Notebook have some problem then them use my computer to push git.
